ALTER TABLE `forbes`.`fb_fh` MODIFY COLUMN `name` VARCHAR(100)  CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '姓名',
 CHANGE COLUMN `xb` `gender` VARCHAR(10)  CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT 0 COMMENT '性别',
 MODIFY COLUMN `birthday` INTEGER UNSIGNED DEFAULT NULL COMMENT '生日',
 CHANGE COLUMN `grjl` `comment` TEXT  CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '个人经历',
 DROP COLUMN `nl`,
 DROP COLUMN `jrpm`,
 CHANGE COLUMN `gj` `country` VARCHAR(100)  CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '中国' COMMENT '国家',
 CHANGE COLUMN `fh_zp` `image` VARCHAR(255)  CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '照片地址';
