CREATE TABLE  `forbes`.`fb_file_list_items` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `category_id` int(11) DEFAULT NULL COMMENT '新闻类别ID',
  `priority` int(11) DEFAULT '100' COMMENT '优先级',
  `click_count` int(11) DEFAULT '0' COMMENT '点击次数',
  `is_adopt` int(11) DEFAULT '0' COMMENT '是否发布',
  `forbbide_copy` int(11) DEFAULT NULL COMMENT '禁止复制',
  `tags` varchar(255) DEFAULT NULL COMMENT '标签',
  `title` text COMMENT '标题',
  `short_title` text COMMENT '短标题',
  `description` longtext COMMENT '简介',
  `content` longtext COMMENT '内容',
  `created_at` datetime DEFAULT NULL COMMENT '创建时间',
  `last_edited_at` datetime DEFAULT NULL COMMENT '最后编辑时间',
  `publisher` varchar(255) DEFAULT NULL COMMENT '发布者',
  `keywords` varchar(255) DEFAULT NULL COMMENT '关键词',
  `news_type` varchar(255) DEFAULT '1' COMMENT '新闻类型',
  `file_name` varchar(255) DEFAULT NULL COMMENT '文件新闻的文件名',
  `target_url` varchar(255) DEFAULT NULL COMMENT '链接新闻的链接地址',
  `photo_src` varchar(255) DEFAULT NULL COMMENT '图片地址',
  `video_photo_src` varchar(255) DEFAULT NULL COMMENT '视频图片地址',
  `image_flag` int(10) unsigned DEFAULT '0' COMMENT '是否是图片新闻',
  `video_flag` int(10) unsigned DEFAULT '0' COMMENT '是否是视频新闻',
  `video_src` varchar(255) DEFAULT NULL COMMENT '视频地址',
  `language_tag` int(11) DEFAULT '0',
  `author` varchar(255) DEFAULT NULL COMMENT '作者',
  `related_news` varchar(100) DEFAULT NULL COMMENT '相关新闻ID，记录相关新闻的id，使用，分割',
  `pdf_src` varchar(255) DEFAULT NULL COMMENT 'pdf源文件',
  `ad_id` int(11) DEFAULT NULL,
  `sub_headline` varchar(100) DEFAULT NULL COMMENT '子头条',
  `wap_title` varchar(256) DEFAULT NULL COMMENT 'wap标题',
  `author_id` int(11) DEFAULT NULL,
  `author_type` int(10) unsigned DEFAULT NULL COMMENT '1',
  `author_image` varchar(255) DEFAULT NULL,
  `top_info` text COMMENT '头信息',
  `set_up` int(10) unsigned DEFAULT '0' COMMENT '是否置顶',
  `list_id` int(11) NOT NULL COMMENT '所属榜单ID',
  PRIMARY KEY (`id`),
  KEY `Index_2` (`created_at`),
  KEY `Index_3` (`category_id`,`is_adopt`),
  KEY `Index_5` (`tags`),
  KEY `Index_6` (`is_adopt`)
) ENGINE=MyISAM AUTO_INCREMENT=29 DEFAULT CHARSET=utf8
